using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HelperLibrary.Core.Annotation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examples.Core.Db
{
    [Table("users")]
    public class Person
    {
        [Key]
        [Column("id")]
        [AutoGeneratedColumn]

        public int Id { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }
    }


}
