using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HelperLibrary.Core.Annotation
{
    /// <summary>
    /// Means the column mapping to a property will be generated automaticly.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class AutoGeneratedColumnAttribute : Attribute
    {
    }
}
